import assert from 'node:assert/strict';
import {createGameState,moveStack,neighbors} from '../src/engine';
import {makeRng} from '../src/services/combatSystem';
import {buildMedievalScene} from '../src/screens/medievalScene';
import {visibleMoves,sampleTrack,ArmyTrack} from '../src/screens/armyTimeline';
const state=createGameState(2,9,9,makeRng(91));
const source=state.cells.find(c=>c.owner===0&&c.units>0)!;
const destination=neighbors(state,source).find(c=>!c.offMap)!;
destination.units=0;destination.owner=null;
const before=buildMedievalScene(state,0,true).ground.map(g=>({...g,cell:{...g.cell}}));
moveStack(source,destination);
const after=buildMedievalScene(state,0,true).ground;
assert.equal(visibleMoves(before,after).length,1,'이동 한 번은 한 번만 재생한다');
assert.equal(visibleMoves(after,after).length,0,'다시 렌더링하거나 턴을 넘겨도 과거 행군을 반복하지 않는다');
const hidden=after.map(g=>g.cell.id===destination.id?{...g,seen:false}:g);
assert.equal(visibleMoves(before,hidden).length,0,'보이지 않는 목적지를 애니메이션으로 드러내지 않는다');
const recruited=before.map(g=>g.cell.id===destination.id?{...g,cell:{...g.cell,units:1}}:g);
assert.equal(visibleMoves(before,recruited).length,0,'징병을 이동으로 해석하지 않는다');
const track:ArmyTrack={from:[0,0,0],to:[1,0,0],start:0,duration:2.8,battle:true,win:true};
assert.equal(sampleTrack(track,.3).action,'walk');
assert.equal(sampleTrack(track,1.5).action,'attack');
assert.equal(sampleTrack(track,2.8).progress,1,'승자는 목적지에 도착한다');
assert.equal(sampleTrack({...track,win:false},2.8).progress,0,'패자는 출발 위치로 물러난다');
assert(['hit','block'].includes(sampleTrack({...track,defender:true},1.5).action));
console.log('행군 감지·반복 방지·시야 비노출·징병 구분·전투 단계 검증 통과');
