import assert from 'node:assert/strict';
import * as T from 'three';
import {exampleBattle} from '../src/screens/battleExamples';
import {attackLead,ATTACK_LEAD,bakeBattleMovement} from '../src/screens/battleReplay';
import {testKnightScene} from './knight-test-model';
import {buildFighter} from '../src/screens/fighterAppearance';
import {buildDuelContacts} from '../src/screens/duelContacts';
import {poseBattleActors,swordContact} from '../src/screens/battleContacts';
const plan=exampleBattle(0),movement=bakeBattleMovement(plan);
const actors=plan.actors.map(a=>{const rig=buildFighter(testKnightScene(),a.kind);new T.Group().add(rig.mesh);return {rig,shape:buildDuelContacts(rig)};});
const parry=plan.exchanges.find(e=>e.heavy&&e.defense==='parry')!,fatal=plan.exchanges.find(e=>e.heavy&&e.fatal)!;
assert(parry&&fatal,'real battle includes a heavy parry and a heavy finisher');
assert(attackLead(parry)>ATTACK_LEAD+.3,'heavy attack visibly telegraphs before a normal cut');
const pose=(t:number)=>poseBattleActors(plan,t,movement.sample(t),actors,()=>0);
pose(parry.at);
assert(swordContact(actors[parry.attacker],actors[parry.target]),'heavy parry meets blade to blade');
const attacker=actors[parry.attacker].rig,origin=attacker.mesh.parent!.position.clone(),away=origin.clone().sub(actors[parry.target].rig.mesh.parent!.position).setY(0).normalize();
const tip=new T.Vector3(0,0,.85).applyMatrix4(attacker.sword.matrixWorld);
pose(parry.at+.24);
const recoil=attacker.mesh.parent!.position.clone().sub(origin).dot(away),bladeRebound=new T.Vector3(0,0,.85).applyMatrix4(attacker.sword.matrixWorld).distanceTo(tip);
assert(recoil>.04,'parried heavy attacker loses forward momentum');assert(bladeRebound>.12,'parry visibly knocks the attacking blade away');
assert.equal(plan.actors[fatal.target].heavyDeath,true);assert.equal(plan.final[1],0);
const death=plan.actors[fatal.target].deathAt;
pose(death-.0001);const before=actors[fatal.target].rig.bones.map(b=>b.getWorldPosition(new T.Vector3()));
pose(death+.0001);const boundaryJump=Math.max(...actors[fatal.target].rig.bones.map((b,i)=>b.getWorldPosition(new T.Vector3()).distanceTo(before[i])));
assert(boundaryJump<.025,`heavy hit must flow into collapse: ${boundaryJump}`);
pose(death+2.3);const landed=actors[fatal.target].rig.bones[8].getWorldPosition(new T.Vector3());
pose(death+3);assert(actors[fatal.target].rig.bones[8].getWorldPosition(new T.Vector3()).distanceTo(landed)<1e-5,'fallen victim stays grounded during dissolution');
console.log({heavyWindup:attackLead(parry),recoil,bladeRebound,deathBoundaryJump:boundaryJump,groundedAfterDeath:true});
actors.forEach(a=>a.rig.dispose());
