import React from 'react';
import {View,Text,TouchableOpacity,StyleSheet,useWindowDimensions} from 'react-native';
import Svg,{Path,Line} from 'react-native-svg';
import type {Cell,GameState} from '../engine';

export function RoyalCrest({color='#1c5389',size=44}:{color?:string;size?:number}){return <Svg width={size} height={size*1.2} viewBox="0 0 60 72"><Path d="M3 3H57V48L30 69 3 48Z" fill={color} stroke="#c2a164" strokeWidth={2}/><Path d="M30 14C12 28 22 34 30 39C38 31 48 27 30 14M29 40C9 22 9 48 23 40M31 40C51 22 51 48 37 40" fill="#ebcd85" stroke="#ebcd85" strokeWidth={2}/><Line x1={30} y1={32} x2={30} y2={56} stroke="#ebcd85" strokeWidth={3}/><Line x1={18} y1={48} x2={42} y2={48} stroke="#ebcd85" strokeWidth={3}/></Svg>;}
type Props={state:GameState;player:number;selected:Cell|null;myTurn:boolean;income:number;readyCastles:number;recruitCost:number;fortCost:number;canFort:boolean;note:string;vassals:number;onRecruit:()=>void;onEnd:()=>void;onFort:()=>void;onMenu:()=>void;onSettings:()=>void;onDiplo:()=>void;onVassals:()=>void;onDetails:()=>void;onMap:()=>void};
export default function RealmHUD(p:Props){
 const {width,height}=useWindowDimensions(),small=width<900||height<500,me=p.state.nations[p.player],cell=p.selected,own=cell?.owner===p.player;
 const button=(label:string,onPress:()=>void,disabled=false)=> <TouchableOpacity key={label} accessibilityRole="button" accessibilityLabel={label} onPress={onPress} disabled={disabled} style={[s.button,disabled&&{opacity:.4}]}><Text style={s.buttonText}>{label}</Text></TouchableOpacity>;
 return <View pointerEvents="box-none" style={[StyleSheet.absoluteFill,{zIndex:20}]}>
   <View style={[s.top,small&&s.topSmall]}>
     <View style={s.brand}><RoyalCrest color={me.color} size={small?28:39}/><View><Text style={[s.title,small&&{fontSize:17}]}>왕국 연대기</Text><Text style={s.caption}>{me.name} · {p.state.turn}턴</Text></View></View>
     <View style={s.resource}><Text style={s.gold}>◉ {Math.floor(me.gold)} G</Text><Text style={s.caption}>{p.income>=0?'+':''}{p.income.toFixed(1)} / 턴</Text></View>
     {!small&&<Text style={s.caption}>정의 {Math.round(me.justice)} · 공포 {Math.round(me.fear)}{'\n'}지금 차례 · {p.state.nations[p.state.current].name}</Text>}
     <View style={[s.actions,small&&{marginLeft:0}]}>{button('외교',p.onDiplo,!p.myTurn)}{button('국정',p.onDetails)}{button('설정',p.onSettings)}{button('2D',p.onMap)}{button('메뉴',p.onMenu)}</View>
   </View>
   {(!small||me.unpaidTurns>0)&&<View pointerEvents="none" style={[s.news,small&&{top:116,left:8,right:8}]}><Text style={[s.caption,me.unpaidTurns>0&&{color:'#ffbd87'}]} numberOfLines={2}>{me.unpaidTurns>0?`급여 체납 ${me.unpaidTurns}턴 · 체납이 계속되면 병력이 이탈합니다`:p.state.log.slice(-1)[0]||'문장기를 누르면 부대를 선택합니다'}</Text></View>}
   <View style={[s.card,small&&{left:8,right:145,width:Math.max(150,width-161),bottom:8,padding:9}]}>
     <View style={s.cardHead}><RoyalCrest color={cell?.owner!=null?p.state.nations[cell.owner].color:me.color} size={small?24:46}/><View style={{flex:1}}><Text style={s.cardTitle}>{cell?(own?'왕국 부대':'선택한 영토'):'왕국 사령부'}</Text><Text style={s.caption}>{cell?`${own?'내 군대':cell.owner!=null?p.state.nations[cell.owner].name:'중립'} · 병력 ${cell.units}`:'지도 위 문장기로 부대를 선택하세요'}</Text>{cell&&<View style={s.morale}><View style={{height:5,width:`${Math.max(0,Math.min(100,cell.morale))}%`,backgroundColor:'#afb959'}}/></View>}</View></View>
     {cell&&<Text style={s.caption}>사기 {Math.round(cell.morale)} · 피로 {Math.round(cell.exhaustion)} · 행군 {Math.round(cell.march)}</Text>}
     {!!p.note&&<Text style={s.note} numberOfLines={small?2:3}>{p.note}</Text>}
     <View style={s.actions}>{button(p.readyCastles?`징병 · ${p.readyCastles*p.recruitCost}G`:'징병 완료',p.onRecruit,!p.myTurn||!p.readyCastles)}{p.canFort&&button(`요새 · ${p.fortCost}G`,p.onFort,!p.myTurn)}{p.vassals>0&&button(`속국 ${p.vassals}`,p.onVassals)}</View>
   </View>
   <TouchableOpacity accessibilityRole="button" accessibilityLabel="턴 종료" disabled={!p.myTurn} onPress={p.onEnd} style={[s.end,small&&{width:128,right:8,bottom:8},!p.myTurn&&{opacity:.55}]}><Text style={s.endText}>{p.myTurn?'턴 종료':'상대 차례'}</Text><Text style={s.caption}>{p.state.turn}번째 연대기</Text></TouchableOpacity>
 </View>;
}
const s=StyleSheet.create({top:{position:'absolute',top:0,left:0,right:0,minHeight:66,backgroundColor:'rgba(20,23,23,.97)',borderBottomWidth:2,borderBottomColor:'#a68c58',flexDirection:'row',alignItems:'center',paddingHorizontal:18,gap:26},topSmall:{padding:7,gap:10,flexWrap:'wrap'},brand:{flexDirection:'row',alignItems:'center',gap:10},title:{fontFamily:'serif',fontSize:25,color:'#eddbb4',letterSpacing:2},caption:{fontSize:11,color:'#c6bea9'},gold:{color:'#e9c677',fontSize:17,fontWeight:'700'},resource:{borderLeftWidth:1,borderLeftColor:'#62543b',paddingLeft:18,gap:4},actions:{flexDirection:'row',gap:5,flexWrap:'wrap',marginLeft:'auto'},button:{minHeight:38,minWidth:42,paddingHorizontal:10,justifyContent:'center',borderWidth:1,borderColor:'#756343',backgroundColor:'#252b29'},buttonText:{fontSize:12,color:'#e6d7b8'},news:{position:'absolute',top:78,left:20,maxWidth:600,padding:8,backgroundColor:'rgba(18,25,24,.77)'},card:{position:'absolute',left:16,bottom:16,width:370,padding:15,borderWidth:2,borderColor:'#a68c58',backgroundColor:'rgba(19,24,24,.96)',gap:9},cardHead:{flexDirection:'row',alignItems:'center',gap:12},cardTitle:{fontFamily:'serif',fontSize:18,color:'#f1e4c8',marginBottom:5},morale:{height:7,borderWidth:1,borderColor:'#6e6846',backgroundColor:'#121919',marginTop:7},note:{color:'#ddc287',fontSize:11},end:{position:'absolute',right:16,bottom:178,width:208,minHeight:60,borderWidth:2,borderColor:'#c3a264',backgroundColor:'#112b3f',alignItems:'center',justifyContent:'center',gap:4},endText:{fontFamily:'serif',color:'#f1e2bf',fontSize:21}});
